export const DEFAULT_HEADER = 'Заголовок по умолчанию';
export const HEADER_BACK = 'Заголовок c кнопкой назад';
export const HEADER_DATE = 'Заголовок c датой';
export const HEADER_FAVORITE = 'Заголовок c кнопкой избранное';
export const HEADER_NOTIFICATION = 'Заголовок c кнопкой уведомления';
export const HEADERS_DIFFERENT_SPACING = 'Заголовки c разными отступами';
export const HEADER_BACKGROUND = 'Заголовки c разными задними планами';
export const HEADER_BREADCRUMBS = 'Заголовки c компонентом Breadcrumbs';
export const HEADER_CHILDREN = 'Заголовок c вложенным компонентом после title';
