declare const _default: import("@storybook/types").ComponentAnnotations<import("@storybook/react/dist/types-0fc72a6d").R, import('../../DatePicker/types').DatePickerRegularProps | import('../../DatePicker/types').DateTimePickerRegularProps | import('../../DatePicker/types').DateTimeSecondsPickerRegularProps | import('../../DatePicker/types').DatePickerPeriodProps | import('../../DatePicker/types').DatePickerUnFullPeriodProps | import('../../DatePicker/types').DatePickerPeriodShiftProps>;
export default _default;
export declare const Default: () => JSX.Element;
export declare const WithColored: () => JSX.Element;
export declare const LevelMonth: () => JSX.Element;
export declare const LevelQuarter: () => JSX.Element;
export declare const LevelYear: () => JSX.Element;
export declare const EnglishDatepicker: () => JSX.Element;
export declare const EnabledHoursFromTo: () => JSX.Element;
export declare const EnabledMinutesFromTo: () => JSX.Element;
export declare const EnabledFromTo: () => JSX.Element;
export declare const WithTime: () => JSX.Element;
export declare const WithSeconds: () => JSX.Element;
export declare const Period: () => JSX.Element;
export declare const PeriodMonth: () => JSX.Element;
export declare const PeriodQuarter: () => JSX.Element;
export declare const PeriodYear: () => JSX.Element;
export declare const PeriodWithShift: () => JSX.Element;
export declare const PeriodWithCustomShift: () => JSX.Element;
export declare const LabelWithDisabled: () => JSX.Element;
export declare const DisableChangesOnBlur: () => JSX.Element;
export declare const OpenPickerOnInputFocus: () => JSX.Element;
export declare const DatepickerWithPseudo: () => JSX.Element;
export declare const WithoutYear: () => JSX.Element;
export declare const ExtraCompact: () => JSX.Element;
//# sourceMappingURL=DatePicker.stories.d.ts.map