export const DEFAULT_DND = 'DragAndDrop по умолчанию';
export const DND_SIZES = 'DragAndDrop по размерам';
export const DND_FILE_TYPES = 'DragAndDrop по типам файлов';
export const DND_CUSTOM_ACCEPT = 'DragAndDrop с кастомным набором принимаемых файлов';
export const DND_STATUSES = 'DragAndDrop по статусам';
export const DND_SMALL_TEXT = 'DragAndDrop Small-Text';
export const DND_SMALL_ICON = 'DragAndDrop Small-Icon';
export const DND_CUSTOM_ICON = 'DragAndDrop с иконкой';
export const DND_CUSTOM = 'DragAndDrop с самостоятельным компонентом';
