#!/bin/bash

## Clean lib folder && Build package using snowpack configuration
yarn snowpack:build
## Add TS types to package
yarn build:types
## Copy index files to lib root level
cp lib/dist/components/index.js lib/dist/components/index.d.ts lib
## Remove fonts from lib
rm -rf lib/fonts
## Process library files (fix Windows paths and update import paths)
node script/changePath.js