name: CI Pipeline
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: |
          npm install --global yarn
          yarn

      - name: TypeScript check
        run: yarn check-types

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Build library
        run: yarn build

      - name: Build Storybook
        run: yarn storybook:build